apps/belt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product/(?P<id>\d+)$', views.product, name='product'),
    url(r'^create$', views.create, name='create'),
    url(r'^add$', views.add, name='add'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^addproduct/(?P<id>\d+)$', views.addproduct, name='addproduct'),
    url(r'^removeproduct/(?P<id>\d+)$', views.removeproduct, name='removeproduct')
    # url(r'^product/(?P<id>\d+)$', views.product, name='product'),
]

apps/login/urls.py
from django.conf.urls import url
# from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout'),
]

bbelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from apps.awesomeApp.models import User as U, Fruit, Donut, Group
#
# class UAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(U, UAdmin)
#
# class FruitAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Fruit, FruitAdmin)
#
# class DonutAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Donut, DonutAdmin)
#
# class GroupAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Group, GroupAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^wishlist/', include('apps.belt.urls', namespace='wishlist')),
]

apps/belt/models.py
# from __future__ import unicode_literals

# from django.db import models

# Create your models here.
from __future__ import unicode_literals

from django.db import models

from ..login.models import User

class Product(models.Model):
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    adder = models.ForeignKey(User, on_delete=models.CASCADE, related_name='madeproduct')

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
import re
import bcrypt

# EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile (r'^(.*?[a-zA-Z]){2,}.*$')
PASSWORD_REGEX = re.compile(r'[A-Za-z0-9@#$%^&+=]{8,}')

class UserManager(models.Manager):
    def login(self, **kwargs):
      if kwargs is not None:
        errors = { }
        if len(kwargs['password']) ==0:
          errors['password'] = "Please Enter a Password"
        if len(kwargs['username']) ==0:
          errors['username'] = "Please Enter a username"
        if len(errors)!=0:
          return (False, errors)
        else:
          user = self.filter (username = kwargs['username'])
          if not user:
            errors['user'] = "username/password combination not found"
            return (False, errors)
          else:
            if bcrypt.checkpw(kwargs['password'].encode('utf-8'), user[0].password.encode('utf-8')):
              return (True, user[0])
            else:
              errors['user'] = 'username/Password Combination Not Found'
              return (False, errors)

    def register_valid(self,name,username,password,confirm_password):
          error=[]
          if not NAME_REGEX.match(name):
              error.append("name invalid")
          if not NAME_REGEX.match(username):
              error.append("username invalid")
          if not PASSWORD_REGEX.match(password):
              error.append("password too short")
          if confirm_password != password:
              error.append("password is not consistent")
          return error

class User (models.Model):
    name = models.CharField (max_length = 45)
    username = models.CharField (max_length = 45)
    password = models.CharField (max_length = 200)
    date_hired = models.DateField (null = True)
    created_at = models.DateField (auto_now_add = True)
    updated_at = models.DateField (auto_now = True)
    objects = UserManager()

apps/belt/views.py
from django.shortcuts import render, redirect
from ..login.models import User
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Product

def index(request):
    user = User.objects.get(id = request.session['user_id'])
    context = {
    'products':user.product_set.all().exclude(adder__id = request.session['user_id']),
    'myproducts':Product.objects.filter(adder__id=request.session['user_id']),
    'otherproducts':Product.objects.exclude(adder__id=request.session['user_id']),
    }
    return render (request, 'belt/index.html', context)

def create(request):
    return render(request, 'belt/create.html')

def add(request):
    if request.method != 'POST':
        return redirect(reverse('wishlist:index'))
    pname = request.POST['product']
    if len(pname) < 3:
        messages.error('Product name must be longer than 3')
        return redirect(reverse('wishlist:create'))
    user = User.objects.get(id=request.session['user_id'])
    try:
        p = Product.objects.get (name = pname)
    except:
        p = Product.objects.create(name = pname, adder = user)
    p.users.add(user)
    return redirect(reverse('wishlist:index'))

def product(request,id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:index'))
    context = {
    'users':p.users.all(),
    'name':p.name
    }
    return render(request, 'belt/product.html', context)

def removeproduct(request,id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:index'))
    user = User.objects.get(id=request.session['user_id'])
    p.users.remove(user)
    return redirect(reverse('wishlist:index'))

def addproduct(request,id):
    try:
        p = Product.objects.get(id=id)
    except:
        return redirect(reverse('wishlist:index'))
    user = User.objects.get(id=request.session['user_id'])
    p.users.add(user)
    # p.save()
    return redirect(reverse('wishlist:index'))
    
def delete(request,id):
    try:
        p = Product.objects.get(id = id)
    except:
        return redirect(reverse('wishlist:index'))
    if p.adder.id != request.session['user_id']:
        return redirect(reverse('wishlist:index'))
    p.delete()
    return redirect(reverse('wishlist:index'))

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.utils.dateparse import parse_date
from .models import User
import re
from django.contrib import messages
import bcrypt
from django.core.urlresolvers import reverse

NAME_REGEX = re.compile (r'^(.*?[a-zA-Z]){2,}.*$')
PASSWORD_REGEX = re.compile(r'[A-Za-z0-9@#$%^&+=]{8,}')

def index(request):
    return render (request, 'login/index.html')

def logout(request):
    request.session.clear()
    return redirect(reverse('login:index'))

def login(request):
    if request.method =='POST':
        result = User.objects.login(username= request.POST['username'], password = request.POST['password'])
        if result[0]:
            request.session['user_id'] = result[1].id
            request.session['name'] = result[1].name
            request.session['username'] = result[1].username
            return redirect(reverse('wishlist:index'))
        else:
            for error in result[1]:
                messages.add_message(request, messages.INFO, result[1][error])
            return redirect(reverse('login:index'))
    else:
        messages.add_message(request, messages.INFO, 'Please Try Again')
        return redirect(reverse('wishlist:index'))

def register(request):
    name = request.POST['name']
    username = request.POST['username']
    datehired = parse_date(request.POST['datehired'])
    password  = request.POST['password']
    confirm_password  = request.POST['confirm_password']
    errors=User.objects.register_valid(name,username,password,confirm_password)
    if len(errors)>0:
        for error in errors:
            messages.error(request, error)
        return redirect('/')
    else:
        password = password.encode()
        hashed = bcrypt.hashpw(password, bcrypt.gensalt())
        user = User.objects.create (name = name, username = username, password = hashed, date_hired = datehired)
        user.save()
        request.session['user_id'] = user.id

        return redirect('/')

apps/belt/templates/belt/create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Item</title>
</head>
<body>
    <h1>Create a New Wish List Item</h1>
    <div id="header">
        <a href="{% url 'wishlist:index' %}">Home</a>
        <a href="{% url 'login:logout' %}">Logout</a>
    </div>
    <form action="{% url 'wishlist:add' %}" method="post">
  {% csrf_token %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    <p>Item/Product: <input type="text" name="product"></p>
    <input type="submit" name="submit" value="Add">
    </form>

</body>
</html>

apps/belt/templates/belt/index.html
<!DOCTYPE html>
<html>
<head>
    <title>
        <meta charset="utf-8">
        <title>product</title>
         {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'wishlist/css/dashboard.css' %}" media="screen">
    </title>
</head>
<body>
    <div class="container">
        <div id="header">
            <h2>Hello, {{request.session.name}}</h2>
            <a id= "logout" href="{% url 'login:logout' %}">Logout</a>
        </div>
        <div id="mywishlist">
            <h4>Your Wish List:</h4>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date added</th>
                    <th>Action</th>
                </tr>
                {% for product in products %}
                <tr class="border">
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M, Y"}}</td>
                    <td><a href="{% url 'wishlist:removeproduct' id=product.id %}">Remove from my wishlist</a></td>
                </tr>
                {% endfor %}
                 {% for product in myproducts %}
                <tr class='border'>
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M, Y"}}</td>
                    <td><a href="{% url 'wishlist:delete' id=product.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
                <div id="other_wishlist">
            <h4>Other Users' Wish List:</h4>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date added</th>
                    <th>Action</th>
                </tr>
                {% for product in otherproducts %}
                <tr class="border">
                    <td><a href="{% url 'wishlist:product' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.adder.name}}</td>
                    <td>{{product.created_at|date:"M, Y"}}</td>
                    <td><a href="{% url 'wishlist:addproduct' id=product.id %}">Add to my wishlist</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <a id= "create" href="{% url 'wishlist:create' %}">Add Item</a>
    </div>

</body>
</html>

apps/belt/templates/belt/product.html
<!DOCTYPE html>
<html>
<head>
    <title>{{name}}</title>
</head>
<body>
    <h1>{{name}}</h1>
    <div id="header">
        <a href="{% url 'wishlist:index' %}">Home</a>
        <a href="{% url 'login:logout' %}">Logout</a>
        <h5>Users who added this product/item under their wish list:</h5>
        {% for user in users%}
            <p>{{user.name}}</p>
        {% endfor %}
    </div>
</body>
</html>

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Login and Registration</title>
<style>
    #Register, #login{
        display: inline-block;
        margin-right: 50px;
        vertical-align: top;
    }
    h3{
        font-family: sans-serif;
    }
    label{
        display: block;
    }
</style>
</head>
<body>
    <div id="container">
        <div id="Register">
            <h3>Register here:</h3>
            <form action="/register" method="post">
                 {% csrf_token %}
                <label for="name">Name: <input type="text" name="name"></label>
                <label for="username">Username: <input type="text" name="username"></label>
                <label for="password">Password: <input type="password" name="password"></label>
                 <p>*Password should be at least 8 characters</p>
                <label for="confirm_password">Confirm password: <input type="password" name="confirm_password"></label>
                <label for="datehired">Date Hired: <input type="date" name="datehired"></label>
                <input type="submit" name="submit" value="Register">
            </form>
        </div>
        <div id="login">
            <h3>Login here:</h3>
            <form action="/login" method="post">
                {% csrf_token %}
                <label for="username">Username: <input type="text" name="username"></label>
                <label for="password">Password: <input type="password" name="password"></label>
                <input type="submit" name="submit" value="Login">
            </form>
            {% if messages %}
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>